// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VacationSpots12._1.Models;

namespace VacationSpots12._1.Migrations
{
    [DbContext(typeof(VacationContext))]
    [Migration("20220526174224_Buyer")]
    partial class Buyer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VacationSpots12._1.Models.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Backpacking"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Outback"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "City"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Island"
                        });
                });

            modelBuilder.Entity("VacationSpots12._1.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Buyer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Categories")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriesCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesCategoryId");

                    b.ToTable("Vacations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categories = 2,
                            CategoryId = 3,
                            Days = 10,
                            Description = "Get lost in spices and enjoy the Morrocan vibe",
                            ImageName = "marrakech.jpg",
                            Name = "Steamy Nights in Marrakech",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 2,
                            Categories = 1,
                            CategoryId = 2,
                            Days = 7,
                            Description = "Get a front seat view watching Kangaroos on their natural habitat",
                            ImageName = "australia.jpg",
                            Name = "Australian Boxing Show",
                            Price = 12000.0
                        });
                });

            modelBuilder.Entity("VacationSpots12._1.Models.Vacation", b =>
                {
                    b.HasOne("VacationSpots12._1.Models.Categories", null)
                        .WithMany("Vacations")
                        .HasForeignKey("CategoriesCategoryId");
                });

            modelBuilder.Entity("VacationSpots12._1.Models.Categories", b =>
                {
                    b.Navigation("Vacations");
                });
#pragma warning restore 612, 618
        }
    }
}
